In [1]:
#EXP :- 2

In [2]:
# Aim :To perform Operation of Exploratory Data Analysis (EDA).

In [3]:
#Name:Bhavesh Chafekar
#Roll:09
#sec:C
#subject:DSS
#Date:

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()                                      # Get current working directory

'C:\\Users\\BHAVESH'

In [9]:
os.chdir("C:\\Users\\BHAVESH\\OneDrive\\Pictures\\Desktop")             # change directory

In [13]:
data=pd.read_csv("pandu.csv")

In [14]:
data.head()                                      # first 5

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [15]:
data.tail()                                       # last 5

      No       Name    Type1   Type2  Height  Weight  Legendary
145  146    Moltres     Fire  Flying     2.0    60.0          1
146  147    Dratini   Dragon     NaN     1.8     3.3          0
147  148  Dragonair   Dragon     NaN     4.0    16.5          0
148  149  Dragonite   Dragon  Flying     2.2   210.0          0
149  150     Mewtwo  Psychic     NaN     2.0   122.0          1

In [16]:
data.shape                                        # here (cloumns , rows)

(150, 7)

In [17]:
data.columns

Index(['No', 'Name', 'Type1', 'Type2', 'Height', 'Weight', 'Legendary'], dtype='object')

In [18]:
data.info

<bound method DataFrame.info of       No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]>

In [19]:
data.dtypes

No             int64
Name          object
Type1         object
Type2         object
Height       float64
Weight       float64
Legendary      int64
dtype: object

In [20]:
data.size                                         # Row * columns

1050

In [21]:
data.ndim                                         # no. of dimension

2

In [22]:
data.describe()

               No      Height      Weight   Legendary
count  150.000000  150.000000  150.000000  150.000000
mean    75.500000    1.200000   46.231333    0.026667
std     43.445368    0.963634   59.547388    0.161647
min      1.000000    0.200000    0.100000    0.000000
25%     38.250000    0.700000    9.925000    0.000000
50%     75.500000    1.000000   30.000000    0.000000
75%    112.750000    1.500000   56.375000    0.000000
max    150.000000    8.800000  460.000000    1.000000