In [1]:
# Exp :- 1

In [2]:
# Aim : To perform Operation of Data Acquisition

In [3]:
#Name:Bhavesh Chafekar
#Roll:09
#sec:C
#subject:DSS
#Date:

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()                                 #Get current working directory

'C:\\Users\\BHAVESH'

In [12]:
os.chdir("C:\\Users\\BHAVESH\\OneDrive\\Pictures\\Desktop")        # change directory

In [15]:
data=pd.read_csv("pandu.csv")

In [16]:
data.head()                                 # First 5

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [17]:
data.tail()                                   # last 5

      No       Name    Type1   Type2  Height  Weight  Legendary
145  146    Moltres     Fire  Flying     2.0    60.0          1
146  147    Dratini   Dragon     NaN     1.8     3.3          0
147  148  Dragonair   Dragon     NaN     4.0    16.5          0
148  149  Dragonite   Dragon  Flying     2.2   210.0          0
149  150     Mewtwo  Psychic     NaN     2.0   122.0          1

In [18]:
data.head(20)

    No        Name   Type1   Type2  Height  Weight  Legendary
0    1   Bulbasaur   Grass  Poison     0.7     6.9          0
1    2     Ivysaur   Grass  Poison     1.0    13.0          0
2    3    Venusaur   Grass  Poison     2.0   100.0          0
3    4  Charmander    Fire     NaN     0.6     8.5          0
4    5  Charmeleon    Fire     NaN     1.1    19.0          0
5    6   Charizard    Fire  Flying     1.7    90.5          0
6    7    Squirtle   Water     NaN     0.5     9.0          0
7    8   Wartortle   Water     NaN     1.0    22.5          0
8    9   Blastoise   Water     NaN     1.6    85.5          0
9   10    Caterpie     Bug     NaN     0.3     2.9          0
10  11     Metapod     Bug     NaN     0.7     9.9          0
11  12  Butterfree     Bug  Flying     1.1    32.0          0
12  13      Weedle     Bug  Poison     0.3     3.2          0
13  14      Kakuna     Bug  Poison     0.6    10.0          0
14  15    Beedrill     Bug  Poison     1.0    29.5          0
15  16      Pidgey  Normal  Flying     0.3     1.8          0
16  17   Pidgeotto  Normal  Flying     1.1    30.0          0
17  18     Pidgeot  Normal  Flying     1.5    39.5          0
18  19     Rattata  Normal     NaN     0.3     3.5          0
19  20    Raticate  Normal     NaN     0.7    18.5          0

In [19]:
data.tail(20)

      No        Name     Type1   Type2  Height  Weight  Legendary
130  131      Lapras     Water     Ice     2.5   220.0          0
131  132       Ditto    Normal     NaN     0.3     4.0          0
132  133       Eevee    Normal     NaN     0.3     6.5          0
133  134    Vaporeon     Water     NaN     1.0    29.0          0
134  135     Jolteon  Electric     NaN     0.8    24.5          0
135  136     Flareon      Fire     NaN     0.9    25.0          0
136  137     Porygon    Normal     NaN     0.8    36.5          0
137  138     Omanyte      Rock   Water     0.4     7.5          0
138  139     Omastar      Rock   Water     1.0    35.0          0
139  140      Kabuto      Rock   Water     0.5    11.5          0
140  141    Kabutops      Rock   Water     1.3    40.5          0
141  142  Aerodactyl      Rock  Flying     1.8    59.0          0
142  143     Snorlax    Normal     NaN     2.1   460.0          0
143  144    Articuno       Ice  Flying     1.7    55.4          1
144  145      Zapdos  Electric  Flying     1.6    52.6          1
145  146     Moltres      Fire  Flying     2.0    60.0          1
146  147     Dratini    Dragon     NaN     1.8     3.3          0
147  148   Dragonair    Dragon     NaN     4.0    16.5          0
148  149   Dragonite    Dragon  Flying     2.2   210.0          0
149  150      Mewtwo   Psychic     NaN     2.0   122.0          1